version: '3.8'

services:
  amazon-linux-2023:
    image: amazonlinux:2023
    container_name: amazon-linux-2023
    tty: true
    volumes:
      - amazon_linux_2023_data:/data
    working_dir: /data
    command: ["/bin/bash"]

  amazon-linux-2:
    image: amazonlinux:2
    container_name: amazon-linux-2
    tty: true
    volumes:
      - amazon_linux_2_data:/data
    working_dir: /data
    command: ["/bin/bash"]

  amazon-linux-latest:
    image: amazonlinux:latest
    container_name: amazon-linux-latest
    tty: true
    volumes:
      - amazon_linux_latest_data:/data
    working_dir: /data
    command: ["/bin/bash"]

volumes:
  amazon_linux_2023_data:
  amazon_linux_2_data:
  amazon_linux_latest_data:
